---
name: 'aarch64 (qemu) build'

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  arm64_job:
    runs-on: ubuntu-latest
    name: Test on arm64
    concurrency:
      group: qemu-arm64-${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ matrix.CC }}-${{ matrix.LONG_INPUTS }}-${{ matrix.INLINE_ASM }}
      cancel-in-progress: true
    strategy:
      matrix:
        CC: [clang, gcc]
        LONG_INPUTS: [UMASH_LONG_INPUTS=0, UMASH_LONG_INPUTS=1]
        INLINE_ASM: [UMASH_INLINE_ASM=0, UMASH_INLINE_ASM=1]
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Test on arm64 (qemu)
        with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}

          env: |
            CC: ${{ matrix.CC }}
            LONG_INPUTS: ${{ matrix.LONG_INPUTS }}
            INLINE_ASM: ${{ matrix.INLINE_ASM }}

          shell: /bin/sh
          install: |
            apt update
            apt install -y build-essential gcc clang python3 python3-pip python3-venv

          run: |
            $CC -v
            CFLAGS="-g -O2 -std=c99 -W -Wall -Werror -march=armv8-a+crypto -D$LONG_INPUTS -D$INLINE_ASM" t/run-tests.sh
